# Generated by Django 2.2.17 on 2020-12-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='star',
        ),
        migrations.AddField(
            model_name='board',
            name='star',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
