# Generated by Django 2.2.17 on 2020-12-16 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20201215_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='star',
        ),
        migrations.AddField(
            model_name='board',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='board_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
