# Generated by Django 2.2.17 on 2020-12-16 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20201216_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='visibility',
            field=models.CharField(choices=[('Private', 'private'), ('Team', 'team'), ('Public', 'public')], default='team', max_length=6),
        ),
    ]
