# Generated by Django 2.2.17 on 2020-12-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_auto_20201216_1424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['is_favorite']},
        ),
    ]
