# Generated by Django 2.2.17 on 2020-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_auto_20201218_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
    ]
